include: package:flutter_lints/flutter.yaml

linter:
  rules:
analyzer:
  errors:
    missing_return: error
    must_be_immutable: error
    must_call_super: error
    invalid_use_of_protected_member: error
    parameter_assignments: error
    sort_unnamed_constructors_first: ignore
    sort_pub_dependencies: ignore
    invalid_annotation_target: ignore
  exclude:
   - '**.freezed.dart'
   - '**.g.dart'
   - '**.config.dart'
   - '**/generated_plugin_registrant.dart'

    
